### ISSUE TITLE
add filter on template allowing custom template

### ISSUE THREAD

**Issue by soderlind** [DekodeInteraktiv/hogan-banner#43]
It would be nice to be able to load a custom template, could you apply a filter on?:

https://github.com/DekodeInteraktiv/hogan-banner/blob/c6ef40ce9582a01912375082c2a9b631ee4f1513/class-banner.php#L122

eg: 

```php
$this->template =  applt_filter( 'hogan/module/banner/template',  __DIR__ . '/assets/template.php' );
```

**Comment by pederan** [comment]
Already possible using filter in core: https://github.com/DekodeInteraktiv/hogan-core/blob/master/includes/class-module.php#L301
